### ISSUE TITLE
attempt to index global 'khalorg' (a nil value)

### ISSUE THREAD

**Issue by agenbite** [BartSte/nvim-khalorg#1]
First of all: a big thank you for khalorg! It's just what I needed.

Then, while trying to install the nvim plugin, I get this error message `E5108: Error executing lua [string ":lua"]:57: attempt to index global 'khalorg' (a nil value)`. 

I'm not very proficient in lua, do you have any clue why this is happening?

**Comment by BartSte** [comment]
Hey, I am glad to help. Did you install khalorg trough pip? Also, how does your config look like? You can also checkout my dotfiles repo for an khalorg example.

**Comment by agenbite** [comment]
Thanks! By lookig at your dotfiles I found that you assign the `require` statement to a `khalorg` variable. Doing that solved my problem! (But I have never seen such an assignment before...)

**Comment by BartSte** [comment]
I see your confusion now. I updated the docs.
